#pragma once
enum class GameEvent : int
{
	//Jumper Events
	EVENT_JUMPER_JUMPED,
	EVENT_JUMPER_COLOR_CHANGE,
	EVENT_JUMPER_LANDED,
	EVENT_JUMPER_SAVED_BY_DISK,
	EVENT_JUMPER_FELL_OFF_GRID,
	EVENT_JUMPER_WILL_FALL_OFF,

	//Character Events
	EVENT_CHARACTER_LOST_LIFE,
	EVENT_CHARACTER_DIED,
	EVENT_PLAYER_SCORED,

	//Enemy Specific
	EVENT_ENEMY_SPAWNED,
	EVENT_ENEMY_FALLS,

	//Level Specific
	EVENT_LEVEL_RESET
};