#pragma once
enum class Event : int
{
	//Jumper Events
	EVENT_JUMPER_JUMPED,
	EVENT_JUMPER_COLOR_CHANGE,
	EVENT_JUMPER_LANDED,
	EVENT_JUMPER_SAVED_BY_DISK,
	EVENT_JUMPER_FELL_OFF_GRID,
	EVENT_OBJECT_COLLIDE,


	EVENT_CHARACTER_LOST_LIFE,
	EVENT_PLAYER_DIED,
	EVENT_PLAYER_SCORED,
	EVENT_LEVEL_RESET,

	//Enemy Specific
	EVENT_ENEMY_SPAWNED,
	EVENT_ENEMY_FALLS
	
};
